<a href="https://colab.research.google.com/github/adasko-a/datascience_bootcamp/blob/main/01_wprowadzenie/funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Funkcje statystyczne

In [8]:
A = np.arange(30)
A = A.reshape(5,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
A.sum()

np.int64(435)

In [10]:
A.min()

np.int64(0)

In [13]:
np.min(A,axis=1)

array([ 0,  6, 12, 18, 24])

In [14]:
np.max(A,axis=1)

array([ 5, 11, 17, 23, 29])

In [15]:
np.median(A)

np.float64(14.5)

In [16]:
np.mean(A)

np.float64(14.5)

In [17]:
np.std(A)

np.float64(8.65544144839919)

In [18]:
np.var(A)

np.float64(74.91666666666667)