<a href="https://colab.research.google.com/github/adasko-a/datascience_bootcamp/blob/main/01_wprowadzenie/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Podstawy

In [ ]:
!pip install numpy

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
d1 = np.array([1,2,3])
print(type(d1),d1.shape,d1.ndim,d1.dtype)

<class 'numpy.ndarray'> (3,) 1 int64


In [ ]:
d2 = np.array([[1.1,2.2,3.3],[4.3,5.3,6.3]])
print(d2.shape,d2.ndim,d2.dtype)

(2, 3) 2 float64


In [ ]:
d3 = np.array([[[2,3,4],[2,3,4]],[[3,2,3],[5,6,7]]])
print(d3.shape,d3.ndim,d3.dtype)

(2, 2, 3) 3 int64


# Typy danych

In [ ]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.3,2.2,3.3])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1,2,26],dtype='int8')
A.dtype

dtype('int8')

In [ ]:
A = np.array([1,2,3],dtype='complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.3,2.2,3.3],dtype='uint')
A.dtype
A

array([1, 2, 3], dtype=uint64)

In [ ]:
A = np.array([True,False])
A.dtype

dtype('bool')

# Tworzenie tablic

In [ ]:
np.zeros(shape=(4,10),dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(8,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full(shape=(3,3),fill_value=4,dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10,100,10,dtype='int')

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.linspace(start=0,stop=11,num=12)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
A = np.arange(15)
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Operacje na tablicach

In [3]:
A = np.array([3,1,2,3,9])
B = np.array([3,2,1,5,6])

In [4]:
A+B

array([ 6,  3,  3,  8, 15])

In [5]:
A-B

array([ 0, -1,  1, -2,  3])

In [6]:
A/B

array([1. , 0.5, 2. , 0.6, 1.5])

In [7]:
A+3

array([ 6,  4,  5,  6, 12])

In [8]:
2*A + 3*B

array([15,  8,  7, 21, 36])

In [10]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])

In [11]:
X*Y

array([[6, 0],
       [2, 0]])

In [12]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [13]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [14]:
X @ Y

array([[  3,   6],
       [-12,   0]])

# Generowanie liczb pseudolosowych

In [15]:
np.random.seed(0)


In [16]:
np.random.randn()

1.764052345967664

In [19]:
np.random.randn(10,3)

array([[ 0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842],
       [-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ],
       [ 0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743]])

In [20]:
np.random.rand(3,3)

array([[0.3595079 , 0.43703195, 0.6976312 ],
       [0.06022547, 0.66676672, 0.67063787],
       [0.21038256, 0.1289263 , 0.31542835]])

In [24]:
np.random.randint(10,122,3)

array([94, 85, 78])

In [25]:
np.random.choice(['a','b','c','d','e'])

np.str_('e')

In [30]:
data= np.random.shuffle(np.arange(10))
print(data)

None


# Funkcje

In [31]:
np.exp(1)

np.float64(2.718281828459045)

In [32]:
np.sqrt(9)

np.float64(3.0)

In [33]:
np.all([2,3,4,1])

np.True_

In [34]:
np.argmax(np.linspace(10,20,30))

np.int64(29)

In [35]:
np.argsort(np.linspace(10,20,30))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

#Indeksowanie i Wycinanie

In [37]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
A[1]

np.int64(1)

In [40]:
A[2:5]

array([2, 3, 4])

In [41]:
A[[0,2,4]]

array([0, 2, 4])

In [46]:
A=A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
A[0]

array([0, 1, 2, 3, 4])

In [48]:
A[:,-1]

array([ 4,  9, 14, 19])

In [49]:
A[2,:]

array([10, 11, 12, 13, 14])

In [50]:
A[2,4]

np.int64(14)

In [51]:
A[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

# Iteracja po tablicach

In [53]:
A = np.arange(20).reshape(4,-1)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [55]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [56]:
for row in A.flat:
  print(row)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


# Zmiana rozmiaru tablic

In [57]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
A.shape

(4, 5)

In [59]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [60]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski logiczne

In [62]:
A = np.arange(-10,10,0.5).reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [63]:
A>0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [64]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [65]:
A[np.bitwise_and(A>-5,A<3)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5])

In [66]:
A[np.bitwise_or(A>-5,A<3)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])